import { Router, type IRouter } from "express";
import healthRouter from "./health.js";
import authRouter from "./auth.js";
import schoolsRouter from "./schools.js";
import teachersRouter from "./teachers.js";
import studentsRouter from "./students.js";
import classesRouter from "./classes.js";
import attendanceRouter from "./attendance.js";
import feesRouter from "./fees.js";
import examsRouter from "./exams.js";
import dashboardRouter from "./dashboard.js";
import notificationsRouter from "./notifications.js";
import resultsRouter from "./results.js";
import assignmentsRouter from "./assignments.js";
import studentPortalRouter from "./student-portal.js";
import parentPortalRouter from "./parent-portal.js";
import teacherPortalRouter from "./teacher-portal.js";
import usersRouter from "./users.js";
import teacherMgmtRouter from "./teacher-management.js";
import accountsRouter from "./accounts.js";
import leaveRouter from "./leave.js";
import timetableRouter from "./timetable.js";
import smsSettingsRouter from "./sms-settings.js";

const router: IRouter = Router();

router.use(healthRouter);
router.use("/auth", authRouter);
router.use("/schools", schoolsRouter);
router.use("/teachers", teachersRouter);
router.use("/students", studentsRouter);
router.use("/classes", classesRouter);
router.use("/attendance", attendanceRouter);
router.use("/fees", feesRouter);
router.use("/exams", examsRouter);
router.use("/results", resultsRouter);
router.use("/dashboard", dashboardRouter);
router.use("/notifications", notificationsRouter);
router.use("/assignments", assignmentsRouter);
router.use("/student", studentPortalRouter);
router.use("/parent", parentPortalRouter);
router.use("/teacher", teacherPortalRouter);
router.use("/users", usersRouter);
router.use("/teacher-mgmt", teacherMgmtRouter);
router.use("/accounts", accountsRouter);
router.use("/leave", leaveRouter);
router.use("/timetable", timetableRouter);
router.use("/sms-settings", smsSettingsRouter);

export default router;
